[package]
name = "tux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.16"
glob = "0.3.0"
owo-colors = "3.4.0"
paris = { version = "1.5.13", features =["macros"]}
search_path = "0.1.3"
